#!/bin/bash
# 1. Force the cursor theme
xsetroot -cursor_name left_ptr
xrdb -merge ~/.Xresources
export XCURSOR_THEME=Bibata-Modern-Ice

# 2. Fix DBus environment
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
dbus-update-activation-environment --systemd --all

# 3. Start background apps
nitrogen --restore &
(sleep 3 && ulauncher --hide-window --no-window-shadow) &
/usr/lib/pipewire-module-xrdp/load_pw_modules.sh &

# 4. Launch Awesome
exec awesome

eval $(/usr/bin/gnome-keyring-daemon --start --components=secrets)
